In [2]:
import  numpy as np

def sigmoid(x):
    return 1/(1 + np.exp(-x))
# sigmoid(5)

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    
    def feed_forward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        print(total)
        return sigmoid(total)
    
weights = np.array([0.5, -0.5])
bias = 0.0

neuron = Neuron(weights, bias)

inputs = np.array([1, 2])

output = neuron.feed_forward(inputs)

print("Neurono atsakymas: ", output )

-0.5
Neurono atsakymas:  0.3775406687981454


In [6]:
import numpy as np

def sigmoid(x):
    return 1 / (1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1-x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input = x
        self.weights1 = np.random.rand(self.input.shape[1], 4)
        self.weights2 = np.random.rand(4,1)
        self.y = y
        self.output = np.zeros(y.shape)

    def feed_forward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

    def backdrop(self):
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output)*sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T, (np.dot(2*(self.y - self.output)*sigmoid_derivative(self.output), self.weights2.T)* sigmoid_derivative(self.layer1)))
    # atnaujinam svorius
        self.weights1 += d_weights1
        self.weights2 += d_weights2

    def train(self, iterations):
        for _ in range(iterations):
            self.feed_forward()
            self.backdrop()

inputs = np.array([[0,0], [0,1], [1,0], [1,1]])
targets = np.array([[0], [1], [1], [0]])

nn = NeuralNetwork(inputs, targets)
nn.train(10000)

print(nn.output)

[[0.01915385]
 [0.98791065]
 [0.98665389]
 [0.0066886 ]]


In [33]:
import numpy  as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

def sigmoid(x):
    return 1 / (1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1-x)

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.weights_input_hidden = np.random.rand(input_size, hidden_size)
        self.weights_output_hidden = np.random.rand(hidden_size, output_size)

    def feed_forward(self, X):
        self.hidden_layer = sigmoid(np.dot(X, self.weights_input_hidden))
        self.output = sigmoid(np.dot(self.hidden_layer, self.weights_output_hidden))

    def backpropagation(self, X, y, learning_rate):
        output_error = y - self.output
        d_output = output_error ** sigmoid_derivative(self.output)
        hidden_error = d_output.dot(self.weights_output_hidden.T)
        d_hidden = hidden_error*sigmoid_derivative(self.hidden_layer)
        self.weights_output_hidden += self.hidden_layer.T.dot(d_output) * learning_rate
        self.weights_input_hidden += X.T.dot(d_hidden) * learning_rate

    def train(self, X, y, epochs, learning_rate):
        for _ in range(epochs):
            self.feed_forward(X)
            self.backpropagation(X, y, learning_rate)

    def predict(self, X):
        self.feed_forward(X)
        return np.round(self.output)
    
    
iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler =  StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

input_size = X_train_scaled.shape[1]
output_size = len(np.unique(y_train))
# TODO
hidden_size = 8
nn = NeuralNetwork(input_size, hidden_size, output_size)

nn.train(X_train_scaled, np.eye(output_size)[y_train], epochs=1000, learning_rate=0.1)
# print(X_test_scaled)
y_pred = nn.predict(X_test_scaled)

print(y_pred)

# [0, 1, 0] == [0, 0, 1]
accuracy = y_pred == np.eye(output_size)[y_test]
print(accuracy)

[[nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]]
[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [F

C:\Users\edita\AppData\Local\Temp\ipykernel_35808\391085211.py:23: RuntimeWarning: invalid value encountered in power
  d_output = output_error ** sigmoid_derivative(self.output)


In [23]:
np.eye(output_size)[y_train]

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1

In [50]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1-x)

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.weights_input_hidden = np.random.rand(input_size, hidden_size)
        self.weights_output_hidden = np.random.rand(hidden_size, output_size)

    def feed_forward(self, X):
        self.hidden_layer = sigmoid(np.dot(X, self.weights_input_hidden))
        self.output = sigmoid(np.dot(self.hidden_layer, self.weights_output_hidden))

    def backpropagation(self, X, y, learning_rate):
        output_error = y - self.output
        d_output = output_error * sigmoid_derivative(self.output)
        hidden_error = d_output.dot(self.weights_output_hidden.T)
        d_hidden = hidden_error * sigmoid_derivative(self.hidden_layer)
        self.weights_output_hidden += self.hidden_layer.T.dot(d_output) * learning_rate
        self.weights_input_hidden += X.T.dot(d_hidden) * learning_rate

    def train(self, X, y, epochs, learning_rate):
        for _ in range(epochs):
            self.feed_forward(X)
            self.backpropagation(X, y, learning_rate)

    def predict(self, X):
        self.feed_forward(X)
        return np.round(self.output)
    
iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

input_size = X_train_scaled.shape[1]
output_size = len(np.unique(y_train))

hidden_size = 8
nn = NeuralNetwork(input_size, hidden_size, output_size)

nn.train(X_train_scaled, np.eye(output_size)[y_train], epochs=100, learning_rate=0.1)

y_pred = nn.predict(X_test_scaled)

print(y_pred)

accuracy = np.mean(y_pred == np.eye(output_size)[y_test])
print(accuracy)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [63]:
import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1-x)

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.weights_input_hidden = np.random.rand(input_size, hidden_size)
        self.weights_output_hidden = np.random.rand(hidden_size, output_size)

    def feed_forward(self, X):
        self.hidden_layer = sigmoid(np.dot(X, self.weights_input_hidden))
        self.output = sigmoid(np.dot(self.hidden_layer, self.weights_output_hidden))

    def backpropagation(self, X, y, learning_rate):
        output_error = y - self.output
        d_output = output_error * sigmoid_derivative(self.output)
        hidden_error = d_output.dot(self.weights_output_hidden.T)
        d_hidden = hidden_error * sigmoid_derivative(self.hidden_layer)
        self.weights_output_hidden += self.hidden_layer.T.dot(d_output) * learning_rate
        self.weights_input_hidden += X.T.dot(d_hidden) * learning_rate

    def train(self, X, y, epochs, learning_rate):
        for _ in range(epochs):
            self.feed_forward(X)
            self.backpropagation(X, y, learning_rate)

    def predict(self, X):
        self.feed_forward(X)
        return np.round(self.output)
    
wine = load_wine()
print(wine)
X = wine.data
y = wine.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
input_size = X_train_scaled.shape[1]
print("Input size: ", input_size)
output_size = len(np.unique(y_train))
print("Output size: ", output_size)

# TODO
hidden_size = 8
nn = NeuralNetwork(input_size, hidden_size, output_size)

nn.train(X_train_scaled, np.eye(output_size)[y_train], epochs=100, learning_rate=0.1)

y_pred = nn.predict(X_test_scaled)

print(y_pred)

accuracy = np.mean(y_pred == np.eye(output_size)[y_test])
print(accuracy)

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [91]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1-x)

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.weights_input_hidden = np.random.rand(input_size, hidden_size)
        self.weights_output_hidden = np.random.rand(hidden_size, output_size)

    def feed_forward(self, X):
        self.hidden_layer = sigmoid(np.dot(X, self.weights_input_hidden))
        self.output = sigmoid(np.dot(self.hidden_layer, self.weights_output_hidden))

    def backpropagation(self, X, y, learning_rate):
        output_error = y - self.output
        d_output = output_error * sigmoid_derivative(self.output)
        hidden_error = d_output.dot(self.weights_output_hidden.T)
        d_hidden = hidden_error * sigmoid_derivative(self.hidden_layer)
        self.weights_output_hidden += self.hidden_layer.T.dot(d_output) * learning_rate
        self.weights_input_hidden += X.T.dot(d_hidden) * learning_rate

    def train(self, X, y, epochs, learning_rate):
        for _ in range(epochs):
            self.feed_forward(X)
            self.backpropagation(X, y, learning_rate)

    def predict(self, X):
        self.feed_forward(X)
        return np.round(self.output)
    
data = load_breast_cancer()
# print('duomenys: ',data)
X = data.data
# print(data.feature_names)
y = data.target
# print(X)
# print("X-so reikšmės: ",X)
# print("y-ko reikšmės: ",y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
input_size = X_train_scaled.shape[1]
print("Input size: ", input_size)
output_size = len(np.unique(y_train))
print("Output size: ", output_size)

# TODO
hidden_size = 8
nn = NeuralNetwork(input_size, hidden_size, output_size)

nn.train(X_train_scaled, np.eye(output_size)[y_train], epochs=1000, learning_rate=0.1)

y_pred = nn.predict(X_test_scaled)

print(y_pred)

accuracy = np.mean(y_pred == np.eye(output_size)[y_test])
print(accuracy)

Input size:  30
Output size:  2
[[0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 

In [93]:
from sklearn.datasets import load_linnerud

data = load_linnerud()
# print('duomenys: ',data)
X = data.data
# print(data.feature_names)
y = data.target
print(y)

[[191.  36.  50.]
 [189.  37.  52.]
 [193.  38.  58.]
 [162.  35.  62.]
 [189.  35.  46.]
 [182.  36.  56.]
 [211.  38.  56.]
 [167.  34.  60.]
 [176.  31.  74.]
 [154.  33.  56.]
 [169.  34.  50.]
 [166.  33.  52.]
 [154.  34.  64.]
 [247.  46.  50.]
 [193.  36.  46.]
 [202.  37.  62.]
 [176.  37.  54.]
 [157.  32.  52.]
 [156.  33.  54.]
 [138.  33.  68.]]
